# File generated by Flopy version 3.10.0 on 03/31/2026 at 17:00:36.
BEGIN options
  XT3D_OFF
END options

BEGIN griddata
  diffc
    CONSTANT  1.00000000E-09
  alh
    CONSTANT       1.50000000
  ath1
    CONSTANT       1.50000000
END griddata

